export default function Privacy() {
  return <main style={{ maxWidth: 720, margin: '48px auto', padding: 24, fontFamily: 'sans-serif', lineHeight: 1.65 }}>
    <h1>Fullbleed Commerce privacy</h1>
    <p>Development preview. Updated October 2, 2026.</p>
    <p>Fullbleed Commerce reads the orders selected by authorized store staff to generate order summaries and packing slips. It processes order items, totals, and billing and shipping addresses in server memory for the requested PDF. It does not save customer orders or generated PDFs to its database.</p>
    <p>The app stores Shopify authorization sessions, seller branding and preferences, and the HTML, CSS and embedded logos you save in Template studio. Templates should use order fields rather than pasted customer details. Enabled Flow automation also stores order identifiers, action-run identifiers, document verification hashes, template revisions, job status, timestamps and download counts. It does not store customer names, addresses or PDFs in the job history. These records are associated with your store and deleted when the app receives Shopify’s authenticated uninstall or shop-deletion notification.</p>
    <p>The app checks subscription status with Shopify. Shopify handles app plan selection and billing. Fullbleed does not collect payment-card details, sell customer data, or use it for advertising. The staging app is hosted on Railway in the United States and is not open to production merchants.</p>
    <p>Private document links expire and can be revoked by the merchant. Opening a link rechecks app access and renders the unchanged order and template in memory. Anyone holding the complete link can download its document while it remains valid; share it only with the intended recipient. Downloads remain on the receiving device.</p>
    <p>Job history is removed after 30 days by an hourly cleanup while the app server is running; outages can delay cleanup. Shopify customer-redaction requests revoke affected links and remove order references and verification hashes. An empty action-run record remains for up to 30 days to prevent a delayed workflow retry from recreating the document.</p>
    <p>When Shopify sends a customer data request, Fullbleed captures an encrypted export of the retained automation metadata and the supplied customer ID or email needed to identify the request. Requested order references and keyed identity hashes support deletion. Authorized store staff can download the export from Privacy requests without a paid plan, then handle the customer response through the store’s privacy process. Fullbleed does not email these exports.</p>
    <p>Outstanding exports are retained until the merchant marks the request handled or Shopify requests erasure. The app shows the 30-day response deadline; overdue requests require action and are not silently deleted. Completion clears the live export, identity hashes and order references immediately. Minimal request receipts remain for 30 days after completion or erasure; uninstall and shop erasure clear the store’s live records. Downloaded copies remain on the recipient’s device.</p>
    <p>Recovery copies of the database are encrypted with a separate key and stored in a private US West bucket. Backups expire for restoration after seven days and are removed after eight days. Encrypted erasure and completion instructions remain for 35 days so restoring an older backup does not revive cleared data. These instructions contain store/order references and keyed customer identifiers, not customer names, addresses or export contents. Cleanup runs at startup and hourly while the app is running; an outage can delay removal. Recovery reapplies these instructions, clears authorization sessions and pauses automation before the restored database is used. The running hosted service creates verified backups daily. Independent key recovery, operator notification and production rollout still need verification before launch. No production customer records are accepted in this development preview.</p>
    <p>For access, correction, deletion or support, contact <a href="mailto:keenan@fullbleed.dev">keenan@fullbleed.dev</a>.</p>
  </main>;
}
