export default function Privacy() {
  return <main style={{ maxWidth: 720, margin: '48px auto', padding: 24, fontFamily: 'sans-serif', lineHeight: 1.65 }}>
    <h1>Fullbleed Commerce privacy</h1>
    <p>Development preview. Updated October 2, 2026.</p>
    <p>Fullbleed Commerce reads the orders selected by authorized store staff to generate order summaries and packing slips. It processes order items, totals, and billing and shipping addresses in server memory for the requested PDF. It does not save customer orders or generated PDFs to its database.</p>
    <p>The app stores Shopify authorization sessions, seller branding and preferences, and the HTML, CSS and embedded logos you save in Template studio. Templates should use order fields rather than pasted customer details. Enabled Flow automation also stores order identifiers, action-run identifiers, document verification hashes, template revisions, job status, timestamps and download counts. It does not store customer names, addresses or PDFs in the job history. These records are associated with your store and deleted when the app receives Shopify’s authenticated uninstall or shop-deletion notification.</p>
    <p>The app checks subscription status with Shopify. Shopify handles app plan selection and billing. Fullbleed does not collect payment-card details, sell customer data, or use it for advertising. A production hosting provider has not been selected and the app is not open to production merchants.</p>
    <p>Private document links expire and can be revoked by the merchant. Opening a link rechecks app access and renders the unchanged order and template in memory. Anyone holding the complete link can download its document while it remains valid; share it only with the intended recipient. Downloads remain on the receiving device.</p>
    <p>Job history is removed after 30 days by an hourly cleanup while the app server is running; outages can delay cleanup. Shopify customer-redaction requests revoke affected links and remove order references and verification hashes. An empty action-run record remains until cleanup to prevent a delayed workflow retry from recreating the document. Customer data-request export must be completed before the paid service launches. No production customer records are accepted in this development preview.</p>
    <p>For access, correction, deletion or support, contact <a href="mailto:keenan@fullbleed.dev">keenan@fullbleed.dev</a>.</p>
  </main>;
}
